language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
# pypy versions
  - "pypy"
  - "pypy3.5"

os:
  - linux

install:
  - python setup.py build
  - pip install coveralls 

script: coverage run --source pycontracts -m unittest discover tests

after_success: coveralls

notifications:
  email: false

